CREATE TABLE IF NOT EXISTS talks (
  url TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  summary TEXT,
  published_date TEXT,
  year INTEGER,
  speaker TEXT,
  company TEXT,
  duration_minutes INTEGER,
  source TEXT,
  conference TEXT,
  track TEXT,
  view_count INTEGER,
  like_count INTEGER,
  topics TEXT NOT NULL DEFAULT '[]',
  has_video INTEGER NOT NULL DEFAULT 0,
  has_slides INTEGER NOT NULL DEFAULT 0,
  has_transcript INTEGER NOT NULL DEFAULT 0,
  score REAL NOT NULL DEFAULT 0,
  decision TEXT NOT NULL DEFAULT 'skip',
  reason TEXT NOT NULL DEFAULT '',
  tags TEXT NOT NULL DEFAULT '[]',
  fetched_at TEXT,
  updated_at TEXT
);
